export const imageUrls = [
  "https://images.unsplash.com/photo-1761839256547-0a1cd11b6dfb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwxfHx8ZW58MHx8fHx8",
];

export const SAMPLE_IMAGES = [
  {
    id: 1,
    src: "https://picsum.photos/seed/a1/400/600",
    title: "Mountain Sunrise",
    author: "Alex R.",
    height: 600,
    saves: "2.4k",
  },
  {
    id: 2,
    src: "https://picsum.photos/seed/b2/400/300",
    title: "Urban Geometry",
    author: "Mia T.",
    height: 300,
    saves: "891",
  },
  {
    id: 3,
    src: "https://picsum.photos/seed/c3/400/500",
    title: "Forest Path",
    author: "Sam K.",
    height: 500,
    saves: "3.1k",
  },
  {
    id: 4,
    src: "https://picsum.photos/seed/d4/400/350",
    title: "Ocean Calm",
    author: "Zoe L.",
    height: 350,
    saves: "1.7k",
  },
  {
    id: 5,
    src: "https://picsum.photos/seed/e5/400/450",
    title: "Desert Dunes",
    author: "Ray M.",
    height: 450,
    saves: "988",
  },
  {
    id: 6,
    src: "https://picsum.photos/seed/f6/400/280",
    title: "City Lights",
    author: "Nora B.",
    height: 280,
    saves: "4.2k",
  },
  {
    id: 7,
    src: "https://picsum.photos/seed/g7/400/520",
    title: "Winter Lake",
    author: "Jin C.",
    height: 520,
    saves: "2.9k",
  },
  {
    id: 8,
    src: "https://picsum.photos/seed/h8/400/380",
    title: "Golden Fields",
    author: "Lena P.",
    height: 380,
    saves: "1.1k",
  },
  {
    id: 9,
    src: "https://picsum.photos/seed/i9/400/460",
    title: "Rainy Street",
    author: "Tom A.",
    height: 460,
    saves: "567",
  },
  {
    id: 10,
    src: "https://picsum.photos/seed/j10/400/320",
    title: "Misty Hills",
    author: "Ava W.",
    height: 320,
    saves: "3.8k",
  },
  {
    id: 11,
    src: "https://picsum.photos/seed/k11/400/560",
    title: "Coastal Cliff",
    author: "Ben S.",
    height: 560,
    saves: "1.4k",
  },
  {
    id: 12,
    src: "https://picsum.photos/seed/l12/400/300",
    title: "Autumn Park",
    author: "Cleo F.",
    height: 300,
    saves: "772",
  },
  {
    id: 13,
    src: "https://picsum.photos/seed/m13/400/420",
    title: "River Bend",
    author: "Omar D.",
    height: 420,
    saves: "2.2k",
  },
  {
    id: 14,
    src: "https://picsum.photos/seed/n14/400/340",
    title: "Starry Night",
    author: "Isla G.",
    height: 340,
    saves: "5.0k",
  },
  {
    id: 15,
    src: "https://picsum.photos/seed/o15/400/490",
    title: "Bamboo Grove",
    author: "Kai H.",
    height: 490,
    saves: "1.8k",
  },
  {
    id: 16,
    src: "https://picsum.photos/seed/p16/400/310",
    title: "Skyline Dusk",
    author: "Fay J.",
    height: 310,
    saves: "3.3k",
  },
];
